name: style

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  BUILD_TYPE: Release

jobs:
  style:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Check Style
      run: ./utils/format -n

